swagger: "2.0"
info:
  description: REST API with Flask, SQLAlchemy and Connexion
  version: "1.0.0"
  title: REST API
consumes:
  - application/json
produces:
  - application/json
basePath: /api

paths:
  /user:
    get:
      operationId: user.read_all
      tags:
        - User
      summary: one of the required RESTful API calls
      description: gets a list of all Users
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: integer
                  description: user id
                username:
                  type: string
                  description: unique username
                first_name:
                  type: string
                  description: first name
                surname:
                  type: string
                  description: family name
                contact_details:
                  type: array
                  items:
                    properties:
                      contact_detail_id:
                        type: integer
                      email:
                        type: string
                        description: email address
                      created_on:
                        type: string
                        description: timestamp when email address was created
    post:
      operationId: user.create
      tags:
        - User
      summary: one of the required RESTful API calls
      description: creates new User
      parameters:
        - name: user
          in: body
          description: user to create
          required: True
          schema:
            type: object
            properties:
              username:
                type: string
                description: unique username
              first_name:
                type: string
                description: first name
              surname:
                type: string
                description: family name
      responses:
        201:
          description: success
          schema:
            properties:
              user_id:
                type: integer
                description: user id
              username:
                type: string
                description: username
              first_name:
                type: string
                description: first name
              surname:
                type: string
                description: family name

  /user/{user_id}:
    get:
      operationId: user.get_by_id
      tags:
        - User
      summary: one of the required RESTful API calls
      description: gets a user by id
      parameters:
        - name: user_id
          in: path
          description: id of required user
          type: integer
          required: True
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              user_id:
                type: integer
                description: user id
              username:
                type: string
                description: username
              first_name:
                type: string
                description: first name
              last_name:
                type: string
                description: family name
              contact_details:
                type: array
                items:
                  properties:
                    contact_detail_id:
                      type: integer
                      description: email id
                    email:
                      type: string
                      description: email address
                    created_on:
                      type: string
                      description: timestamp when email was created
    put:
      operationId: user.update
      tags:
        - User
      summary: one of the required RESTful API calls
      description: updates a user
      parameters:
        - name: user_id
          in: path
          description: id of a user that needs to be updated
          type: integer
          required: True
        - name: user
          in: body
          schema:
            type: object
            properties:
              username:
                type: string
                description: username
              first_name:
                type: string
                description: first name
              surname:
                type: string
                description: family name
      responses:
        200:
          description: success
          schema:
            properties:
              user_id:
                type: integer
                description: user id
              username:
                type: string
                description: username
              first_name:
                type: string
                description: first name
              surname:
                type: string
                description: family name

    delete:
      operationId: user.delete
      tags:
        - User
      summary: one of the required RESTful API calls
      description: deletes a contaact with given id
      parameters:
        - name: user_id
          in: path
          type: integer
          description: id of a user to delete
          required: True
      responses:
        200:
          description: success


  /user/{user_id}/contact_detail:
    post:
      operationId: contact_detail.create
      tags:
        - ContactDetail
      summary: one of the required RESTful API calls
      description: creates new Email for given User
      parameters:
        - name: user_id
          in: path
          description: user id
          type: integer
          required: True
        - name: contact_detail
          in: body
          description: ContactDetail object
          required: True
          schema:
            type: object
            properties:
              email:
                type: string
                description: email address
      responses:
        201:
          description: success
          schema:
            properties:
#              user_id:
#                type: interger
#                description: user id
              contact_detail_id:
                type: integer
                description: contact detail id
              email:
                type: string
                description: email address
              created_on:
                type: string
                description: creation date

  /user/{user_id}/contact_detail/{contact_detail_id}:
    get:
      operationId: contact_detail.get_by_id
      tags:
        - ContactDetail
      summary: reads a contact_details associated with given user
      description: reads a contact_details associated with given user
      parameters:
        - name: user_id
          in: path
          description: user id
          type: integer
          required: True
        - name: contact_detail_id
          in: path
          description: contact_detail id
          type: integer
          required: True
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              contact_detail_id:
                type: integer
                description: contact_detail id
              user_id:
                type: integer
                description: user id
              email:
                type: string
                description: email
              created_on:
                type: string
                description: timestamp of record creation

    put:
      operationId: contact_detail.update
      tags:
        - ContactDetail
      summary: updates a contact_details associated with given user
      description: updates a contact_detail associated with given user
      parameters:
        - name: user_id
          in: path
          description: user id
          type: integer
          required: True
        - name: contact_detail_id
          in: path
          description: contact_detail id
          type: integer
          required: True
        - name: contact_detail
          in: body
          schema:
            type: object
            properties:
              email:
                type: string
                description: email in contact_detail
      responses:
        200:
          description: success
          schema:
            properties:
              contact_detail_id:
                type: integer
                description: contact_detail id
              user_id:
                type: integer
                description: user id
              email:
                type: string
                description: email address
              created_on:
                type: string
                description: timestamp of record creation

    delete:
      operationId: contact_detail.delete
      tags:
        - ContactDetail
      summary: deletes a contact detail for given user
      description: deletes a contact detail for given user
      parameters:
        - name: user_id
          in: path
          description: user id
          type: integer
          required: True
        - name: contact_detail_id
          in: path
          description: contact detail id to delete
          type: integer
          required: True
      responses:
        200:
          description: success